[WIP] - Atualiza process management process
fga-eps-mds/2023-1-CAPJu-Services pull request #25
Opened 2023-07-13 23:28 UTC by zpeniel09

## Issue

Closes fga-eps-mds/2023-1-CAPJu-Doc#issue_number

## Descrição

## Revisão

- [ ] Critério 1
- [ ] Critério 1
- [ ] Critério 1

## Pre-merge checklist

- [ ] O Pull Request refere-se a um único assunto, um título claro e uma descrição em frases gramaticalmente corretas e completas.
- [ ] A ramificação está atualizada com a branch Develop.
- [ ] Os commits atendem o padrão especificado na política de contribuição.

2023-07-17 00:10 UTC, sergiosacj requested changes

2023-07-17 00:10 UTC, sergiosacj commented on ProcessManagement/tests/__tests__/test_process_controllers.js
> +      // processController.processService.findAll
Pode remover todas as linhas comentadas, não tem porque comentar código.

Se não vai ser usado pode remover, se precisar recuperar o código é só usar o Git.

2023-07-17 00:10 UTC, sergiosacj commented on ProcessManagement/tests/__tests__/test_process_controllers.js
> +      const mockProcesses = [{ id: 1, name: 'Process 1', record: '123Abc' }, { id: 2, name: 'Process 2', record: '123Abc'}];
Executa o yarn prettify, acho que isso aqui não foi formatado.

2023-07-17 00:10 UTC, sergiosacj commented on ProcessManagement/src/services/flowProcess.js
> +export default FlowProcessService;
Isso aqui é um problema que precisamos discutir, não é para essa FlowProcess existir.

Tínhamos removido ela intencionalmente.

2023-07-17 00:46 UTC, faco400 commented
@sergiosacj Pronto acredito que agora está corrigido. Removi o flowProcess e substitui onde tava usando pelo flowStage . Acredito que assim é o correto

2023-07-17 01:09 UTC, sergiosacj commented
> @sergiosacj Pronto acredito que agora está corrigido. Removi o flowProcess e substitui onde tava usando pelo flowStage . Acredito que assim é o correto

Ficou faltando remover tudo relacionado a flowProcess então, já que não é mais necessário.

2023-07-17 01:59 UTC, faco400 commented
@sergiosacj Verdade! Eu esqueci de tirar a model e até o _index. Dei uma "varrida" e acho que retirei os arquivos restantes

2023-07-17 02:18 UTC, sergiosacj approved these changes

2023-07-18 11:00 UTC, GuilhermeDSa1013 approved these changes
LGTM, boa pessoal

2023-07-18 11:17 UTC, merged