Estrutura serviço de email em classes
fga-eps-mds/2023-1-CAPJu-Services pull request #4
Opened 2023-05-15 14:51 UTC by flavioovatsug

## Issue

Closes fga-eps-mds/2023-1-CAPJu-Doc#111

## Descrição

Atualmente o código é estruturado por funções, todas sendo exportadas sem nenhuma restrição.

## Como solucionar 

Utilizar classe para expor somente o necessário, além de salvar variáveis comuns das funções.

## Revisão
Verifica se os critérios estabelecidos na issue foram realizados
- [x] O código do serviço de e-mail precisa estar estruturado como uma Classe;
- [ ] Os testes precisam ser adaptados para essa nova mudança;
- [ ] O cronjob vai executar um método de uma instância da classe.

## Pre-merge checklist

- [x] O Pull Request refere-se a um único assunto, um título claro e uma descrição em frases gramaticalmente corretas e completas.
- [x] A ramificação está atualizada com a branch Develop.
- [x] Os commits atendem o padrão especificado na política de contribuição.

2023-05-17 16:32 UTC, sergiosacj requested changes
Único ponto que deve mudar:
- Ficou repetitivo ter dois getMailContents, só precisa de um. Podem deixá-lo como público, mas se quiserem deixar como privado vão ter que remover os testes dele (não testamos métodos privados, eles são testados de tabela ao testarmos os métodos públicos que chamam eles).

2023-05-17 16:34 UTC, sergiosacj commented
@flavioovatsug @YanWerlley por enquanto não precisam se preocupar com os commits, quando eu aceitar a gente faz uma call e fazemos rebase para organizar tudo antes do merge.

Outro ponto é que todo PR precisa de 2 revisores, adionem um MDS para revisar esse daqui.

2023-05-17 23:19 UTC, YanWerlley commented
> Único ponto que deve mudar:
> 
> * Ficou repetitivo ter dois getMailContents, só precisa de um. Podem deixá-lo como público, mas se quiserem deixar como privado vão ter que remover os testes dele (não testamos métodos privados, eles são testados de tabela ao testarmos os métodos públicos que chamam eles).

@sergiosacj Removemos a duplicidade e deixamos o método publico e com os testes. Verificaremos mais pra frente a necessidade de privar o método e remover os testes.

2023-05-18 16:49 UTC, sergiosacj commented
Beleza! hoje não vou conseguir parear, mas amanhã ou sábado podemos nos reunir para olhar a questão do rebase e também já realizar o setup do @leomitx10 para ele revisar.

2023-05-20 19:19 UTC, leomitx10 approved these changes

2023-05-20 20:09 UTC, sergiosacj approved these changes

2023-05-20 20:12 UTC, merged